filename: "mock_{{.SrcPackageName | snakecase}}_{{.InterfaceName | snakecase}}.go"
dir: "test/mocks"
pkgname: "mocks"
packages:
  github.com/Sokol111/ecommerce-category-query-service/internal/categorylist:
    interfaces:
      collection:
        config:
          structname: MockCategoryCollection
      Store:
        config:
          structname: MockCategoryStore
  github.com/Sokol111/ecommerce-category-query-service/pkg/model:
    interfaces:
      CategoryListService:
        config:
          structname: MockCategoryListService
