services:
  catserv:
    image: sokol111/${PROJECT_NAME}:latest
    container_name: catserv
    labels:
      - "traefik.http.routers.catserv.rule=Host(`${PROJECT_NAME}.localhost`)"
      - "traefik.http.services.catserv.loadbalancer.server.port=8080"
    networks:
      - shared-network
    environment:
      - APP_ENV=development
      - MONGO_HOST=mongo
      - KAFKA_BROKERS=kafka:29092

networks:
  shared-network:
    external: true
