logger:
  level: "debug"
  development: true

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  replica-set: rs0
  database: "category-query"

kafka:
  brokers: "redpanda:29092"
  schema-registry:
    url: "http://redpanda:8081"
    auto-register-schemas: true
  consumers-config:
    default-group-id: "ecommerce-category-query-service"
    default-auto-offset-reset: "earliest"
    consumers:
      - name: "category-events"
        topic: "catalog.category.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true
      - name: "attribute-events"
        topic: "catalog.attribute.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true
      - name: "tenant-events"
        topic: "tenant.tenant.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true

security:
  token:
    jwks-url: "http://zitadel-api:8080/oauth/v2/keys"
  s2s:
    token-url: "http://zitadel-api:8080/oauth/v2/token"

clients:
  tenant-service:
    base-url: "http://ecommerce-tenant-service:8080"

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false

pprof:
  enabled: true
  port: 6060
