logger:
  level: "debug"
  development: true

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  replica-set: rs0
  database: "category-query"

kafka:
  brokers: "redpanda:29092"
  schema-registry:
    url: "http://redpanda:8081"
    auto-register-schemas: true
  consumers-config:
    default-group-id: "ecommerce-category-query-service"
    default-auto-offset-reset: "earliest"
    consumers:
      - name: "category-events"
        topic: "catalog.category.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true
      - name: "attribute-events"
        topic: "catalog.attribute.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true
      - name: "tenant-events"
        topic: "tenant.tenant.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true

security:
  token:
    public-key: "eb6ebefd6a2b0a304d43c2ccca329aef0a1439d429dbe8ca9b6190622ce38341"
    service-token: "v4.public.eyJleHAiOiIyMDM2LTA0LTA3VDIzOjQ2OjI3KzAyOjAwIiwiaWF0IjoiMjAyNi0wNC0xMFQyMzo0NjoyNyswMjowMCIsIm5iZiI6IjIwMjYtMDQtMTBUMjM6NDY6MjcrMDI6MDAiLCJwZXJtaXNzaW9ucyI6WyJwcm9kdWN0czpyZWFkIiwiY2F0ZWdvcmllczpyZWFkIiwiYXR0cmlidXRlczpyZWFkIiwidGVuYW50czpyZWFkIl0sInJvbGUiOiJzZXJ2aWNlX2FjY291bnQiLCJzZXJ2aWNlX25hbWUiOiJjYXRlZ29yeS1xdWVyeS1zZXJ2aWNlIiwic3ViIjoic2VydmljZTpjYXRlZ29yeS1xdWVyeS1zZXJ2aWNlIiwidHlwZSI6ImFjY2VzcyJ94uVyQcokUZSyJcLgzp5qKmgsg8w89Ar9tYnknQBuPh0pgMrZBhGFaZw6fXWVU4fL_6TK1jIVjDLc06QeiAhWAQ"

clients:
  tenant-service:
    base-url: "http://ecommerce-tenant-service:8080"

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false

pprof:
  enabled: true
  port: 6060
