server:
  port: 8080

mongo:
  host: ""
  port: 27017
  replica-set: rs0
  database: "category-query"

kafka:
  brokers: ""
  consumers-config:
    group-id: "ecommerce-category-query-service"
    auto-offset-reset: "earliest"
    consumers:
      - handler: "categoryCreatedHandler"
        topic: "catalog.category.created.v1"
      - handler: "categoryUpdatedHandler"
        topic: "catalog.category.updated.v1"
