logger:
  level: "debug"

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  replica-set: rs0
  database: "category-query"

kafka:
  brokers: "kafka:29092"
  consumers-config:
    group-id: "ecommerce-category-query-service"
    auto-offset-reset: "earliest"
    consumers:
      - handler: "categoryCreatedHandler"
        topic: "catalog.category.created.v1"
      - handler: "categoryUpdatedHandler"
        topic: "catalog.category.updated.v1"

observability:
  tracing-enabled: true
  metrics-enabled: false
  metrics-interval: 10s
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  prometheus-endpoint: "prometheus-server.observability.svc:9090"